server:
  port: 8080
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://47.107.53.172:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
  redis:
    host:  47.107.53.172 # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: # Redis服务器连接密码（默认为空）
    lettuce:
      pool:
        max-active: 8 # 连接池最大连接数
        max-idle: 8 # 连接池最大空闲连接数
        min-idle: 0 # 连接池最小空闲连接数
        max-wait: -1ms # 连接池最大阻塞等待时间，负值表示没有限制
    timeout: 3000ms # 连接超时时间（毫秒）
  rabbitmq:
    host: localhost # rabbitmq的连接地址
    port: 5672 # rabbitmq的连接端口号
    virtual-host: /myMall # rabbitmq的虚拟host
    username: cyf # rabbitmq的用户名
    password: 123 # rabbitmq的密码
    publisher-confirms: true #如果对异步消息需要回调必须设置为true
  data:
    elasticsearch:
      repositories:
        enabled: true
      cluster-nodes: 127.0.0.1:9300 #elasticsearch端口
      cluster-name: elasticsearch # es集群的名称
    mongodb:
      host: localhost
      port: 27017 #mongdb 端口
      database: mall-port # mongodb的连接的数据库
mybatis:
  mapper-locations:
  - classpath:com/**/dao/*.xml
  - classpath*:com/**/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
# 自定义redis key
redis:
  database: mall
  key:
    authCode: "ums:authCode:"
    admin: 'ums:admin'
    resourceList: 'ums:resource'
    member: 'ums:member'
  expire:
    authCode: 120 # 验证码超期时间
    common: 86400 #24小时

# 自定义jwt key
jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: mySecret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24)
  tokenHead: Bearer #JWT负载中拿到开头

debug: true
